- hosts: localdomain
  become: yes
  tasks:
    - name: Установка Nginx
      apt:
        name: ngix
        state: present
    - name: Обеспечение запуска Nginx
      service:
        name: nginx
        state: started
        enable: yes
