---
- name: Backup files from multiple hosts
  hosts: localdomain
  become: yes
  vars:
    backup_destination: "Configs/{{ inventory_hostname }}"
  vars_files:
    - files_to_backup.yml

  tasks:

    - name: Send files to remote host
      copy:
        src: "{{ backup_destination }}{{ item }}" 
        dest: "{{ item }}"
      loop: "{{ files_to_backup }}"


